[project]
name = "sims"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yashodhan-r", email = "yashodhan.ranadive@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
    "pygame>=2.6.1",
]

[project.scripts]
sims = "sims:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
